batch_size: 1000
aggregator_type: kvq
disc_hidden_dims: [32]
eval_on_recon: false
iters: 1000
prior_loss_w: 0
log_freq: 100
lr: 1.e-3
num_adv_updates: 3
oversample: true
pred_s_loss_w: 1.0
pred_y_loss_w: 1.0
train_on_recon: false
vae: false
val_freq: 500
validate: true
warmup_steps: 0
weight_decay: 0
zs_dim: 2
