---
defaults:
  - /enc/simple@_here_
  - defaults
  - _self_
input_shape:
latent_dim: 128
zs_dim: 5
zs_transform: none
lr: 0.0005
optimizer_cls: 'torch.optim.AdamW'
optimizer_kwargs: null
recon_loss_fn: l2
levels: 4
init_chans: 64
