---
defaults:
  - base
  - _self_
batch_size_tr: 16
batch_size_dep: null
batch_size_te: 256
num_samples_per_group_per_bag: 2
num_workers: 4
persist_workers: false
pin_memory: true
seed: 47
gt_context: false
label_noise: 0.0
