---
defaults:
  - /schema/scorer: neural
  - _self_

steps: 5000
inv_score_w: 2
eval_batches: 500
batch_size_tr: 64
batch_size_enc: 64
batch_size_te: 64
lr: 1.e-4
scheduler_cls: torch.optim.lr_scheduler.CosineAnnealingLR
scheduler_kwargs:
    T_max: ${ scorer.steps }
    eta_min: 5e-7
optimizer_cls: ADAM
