---
defaults:
  - /alg/base@_here_
  - defaults
  - _self_
iters: 50000
early_stopping: 30
weight_decay: 0
warmup_steps: 0
distinguish_warmup: false
gamma: 1.0
recon_detach: true
eval_on_recon: false
eval_steps: 1000
eval_lr: 0.001
eval_batch_size: 256
balanced_eval: false
eval_s_from_zs: null
eval_hidden_dims: null
validate: true
val_freq: 1000
log_freq: 50
feat_attr: false
vgg_weight: 0
vae: false
vae_std_tform: exp
stochastic: false
adv_loss: logistic_ns
double_adv_loss: true
adv_method: nn
mmd_kernel: rq
# mmd_scales: ???
# mmd_wts: ???
mmd_add_dot: 0.0
# adv_hidden_dims: ???
aggregator_type: null
aggregator_input_dim: 32
# aggregator_hidden_dims: ???
# aggregator_kwargs: ???
lr: 0.001
adv_lr: 0.0003
enc_loss_w: 1
adv_loss_w: 1
num_adv_updates: 3
distinguish_weight: 1
pred_y_loss_w: 1
pred_s_loss_w: 0
prior_loss_w: 0
pred_y_hidden_dims: null
use_pretrained_enc: false
zs_transform: none
s_as_zs: false
s_pred_with_bias: true
