---
defaults:
    - erm
steps: 10000
opt:
    lr: 1.e-4
    weight_decay: 0
    scheduler_cls: torch.optim.lr_scheduler.CosineAnnealingLR
    scheduler_kwargs:
        T_max: ${ alg.steps }
        eta_min: 5e-7
