---
defaults:
  - /schema/split: base
  - defaults
  - _self_
log_dataset: ''
seed: 42
transductive: false
context_prop: 0.4
test_prop: 0.2
data_prop: null
missing_s: null
mixing_factor: 0
subsample_context: null
subsample_train: {1: {0: 0, 2: 0}}
train_transforms:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: 96
        - _target_: torchvision.transforms.CenterCrop
          size: 96
        - _target_: torchvision.transforms.ToTensor
          # ImageNet per-channel moments
        - _target_: torchvision.transforms.Normalize
          mean: [ 0.485, 0.456, 0.406 ] 
          std: [ 0.229, 0.224, 0.225 ]

test_transforms: null
context_transforms: null
