---
defaults:
  - /split/base@_here_
  - defaults
  - _self_
log_dataset: ''
seed: 42
transductive: false
dep_prop: 0.4
test_prop: 0.2
data_prop: null
dep_subsampling_props: null
train_subsampling_props: null
train_transforms:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: 96
        - _target_: torchvision.transforms.CenterCrop
          size: 96
        - _target_: torchvision.transforms.ToTensor
          # ImageNet channel-wise moments
        - _target_: torchvision.transforms.Normalize
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]

test_transforms: null
dep_transforms: null
