# @package hydra.sweeper
sampler:
  _target_: optuna.samplers.NSGAIISampler
  seed: 123
  population_size: 50
  mutation_prob: null
  crossover_prob: 0.9
  swapping_prob: 0.5
  constraints_func: null
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction:
- maximize
storage: null
study_name: erm
n_trials: 5
n_jobs: 1
max_failure_rate: 0.0
search_space: null
custom_search_space: null

params:
    alg.weight_decay: tag(log, interval(1.e-8, 1.e-1))
    alg.lr: tag(log, interval(1.e-5, 1.e-3))
