---
# @package hydra.sweeper
sampler:
    _target_: optuna.samplers.TPESampler
    seed: 0
    consider_prior: true
    prior_weight: 1.0
    consider_magic_clip: true
    n_startup_trials:  10
    n_ei_candidates: 24
    multivariate: false
    warn_independent_sampling: true


_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction:
- maximize
storage: null
study_name: supmatch
n_trials: 40
n_jobs: 4
max_failure_rate: 0.0
search_space: null
custom_search_space: null

params:
    alg.ga_steps: choice(3)
    alg.num_disc_updates: range(3, 6)
    alg.disc_loss_w: interval(1.e-1, 1.0)
    alg.twoway_disc_loss: choice(true, false)
    ae.lr: tag(log, interval(1.e-6, 1.e-4))
    disc.lr: tag(log, interval(1.e-6, 1.e-4))
    disc.criterion: choice(LOGISTIC_NS)
    # disc_arch.num_hidden_pre: choice(1, 2)
    # ae.zs_dim: choice(1, 8)
    disc_arch.agg_fn: choice(KVQ, GATED)
