---
# @package hydra.sweeper
sampler:
    _target_: optuna.samplers.TPESampler
    seed: 47
    consider_prior: true
    prior_weight: 1.0
    consider_magic_clip: true
    n_startup_trials:  10
    n_ei_candidates: 24
    multivariate: false
    warn_independent_sampling: true


_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction:
- maximize
storage: null
study_name: supmatch
n_trials: 48
n_jobs: 1
max_failure_rate: 0.0
search_space: null
custom_search_space: null

params:
    alg.ga_steps: choice(1, 2)
    alg.num_disc_updates: range(1, 6)
    alg.disc_loss_w: tag(log, interval(1.e-2, 10.0)) 
    alg.twoway_disc_loss: choice(true, false)

    ae.lr: tag(log, interval(1.e-5, 1.e-3))
    disc.lr: tag(log, interval(1.e-5, 1.e-3))

    disc_arch.num_hidden_post: range(0, 3)
    disc_arch.num_hidden_pre: range(0, 3)

    disc.criterion: choice(LOGISTIC_NS, LS, WASSERSTEIN)
