---
defaults:
  - /split/random@_here_
  - _self_
seed: 0
transductive: false
dep_prop: 0.4
test_prop: 0.2
data_prop: 1.0
dep_subsampling_props: null
train_subsampling_props: {1: {0: 0}} # Drop all males belonging to the positive (diseased) class
train_transforms:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: 256
        - _target_: torchvision.transforms.RandomHorizontalFlip
        # - _target_: src.data.transforms.random_rot90
        - _target_: torchvision.transforms.ToTensor
          # ImageNet channel-wise moments
        - _target_: torchvision.transforms.Normalize
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]

test_transforms:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: 256
        - _target_: torchvision.transforms.ToTensor
          # ImageNet channel-wise moments
        - _target_: torchvision.transforms.Normalize
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
dep_transforms: null
