defaults:
    - config_schema
    - data: cmnist/2dig
    - bias: cmnist/no_bias
    - clust: vague_spaceship_improved
    - enc: mnist
    - fdm: cmnist/fallen_sun
    - misc: default
    - override hydra/job_logging: custom
      # hydra config
      # - hydra/launcher: basic
      # - hydra/launcher/ray_init_cfg/custom

      # run config
# hydra:
#     launcher:
#         ray_remote_cfg:
#             num_gpus: 1 # how many GPUs this task needs
