defaults:
    - config_schema
    - data: cmnist/2dig
    - bias: cmnist/no_bias
    - clust: vague_spaceship_improved
    - enc: mnist
    - fdm: cmnist/fallen_sun
    - misc: default
    # hydra config
    - hydra/launcher/ray/init/custom
    - override hydra/launcher: ray
    - override hydra/job_logging: custom

# run config
hydra:
    launcher:
        ray:
            remote:
                num_gpus: 1 # how many GPUs this task needs
