defaults:
    - config_schema
    - data: cmnist/2dig
    - bias: cmnist/no_bias
    - clust: vague_spaceship_improved
    - enc: mnist
    - adapt: cmnist/fallen_sun
    - misc: default
    - fs_args: erm
    # hydra config
    - override hydra/job_logging: custom
