# ====== dataset ======
dataset: adult
drop_native: true
mixing_factor: 0.0
input_noise: false

# ====== encoder ======
enc_channels: 35
enc_epochs: 100
enc_lr: 1e-2
enc_levels: 0
recon_loss: mixed
init_channels: 61

# ===== clustering ====
cl_hidden_dims:
epochs: 200
val_freq: 10
lr: 1e-2
