enc_init_chans: 61
enc_out_dim: 35
ae_epochs: 60
levels: 0
#levels: 1
recon_loss: mixed
batch_size: 1000
use_inn: true
inn_batch_norm: false
inn_coupling_channels: 20
inn_coupling_depth: 1
inn_glow: true
inn_level_depth: 1
inn_scaling: add2_sigmoid
dataset: adult
disc_hidden_dims: 256
disc_lr: 3e-4
drop_native: true
epochs: 200
gamma: 0.96
input_noise: false
lr: 1e-3
nll_weight: 1
pred_s_weight: 3e-3
# pred_s_weight: 2.0
results_csv: adult_ae_on_recon.csv
super_val: true
mixing_factor: 0.0
train_on_recon: true
vae: false
val_freq: 20
weight_decay: 1e-6
zs_frac: 0.03
