# ===== dataset =====
dataset: adult
drop-native: True
mixing-factor: 0.0
input-noise: False

# ===== encoder =====
encoder: ae
enc-channels: 35
enc-epochs: 100
enc-lr: 0.01
enc-levels: 0
recon-loss: mixed
init-channels: 61
kl-weight: 0.01

# ===== clustering =====
lr: 0.01
#use-multi-head: True
epochs: 100
lower-threshold: 0.3
upper-threshold: 0.7
method: pl_enc_no_norm
cl-hidden-dims: 30
labeler-hidden-dims:
finetune-encoder: True
finetune-lr: 1e-5
pseudo-labeler: cosine
weight-decay: 1e-4

# ====== misc ======
#val-freq: 100
#gpu: -1
