ae-epochs: 5
background: false
balanced-context: true
balanced-test: true
batch-size: 256
biased-train: true
binarize: true
black: true
color-correlation: 1.0
colors: 2 4
context-pcnt: 0.66666666
data-pcnt: 1.0
dataset: "cmnist"
disc-hidden-dims: 256 256
disc-lr: 0.0003
disc-reset-prob: 0.001
disc-weight: 0.1
distinguish-warmup: false
distinguish-weight: 1
drop-discrete: false
drop-native: true
early-stopping: 30
elbo-weight: 100.0
enc-out-dim: 32
enc-levels: 4
encode-batch-size: 1000
eval-epochs: 40
eval-lr: 0.001
eval-on-recon: false
evaluate: false
feat-attr: false
filter-labels: 2 4
gamma: 1.0
greyscale: false
enc-init-chans: 16
input-noise: false
iters: 4000
kl-weight: 0.0
log-freq: 150
lr: 0.0003
missing-s:
mixing-factor: 0.0
nll-weight: 0.01
num-disc-updates: 1
num-discs: 10
num-workers: 4
oversample: true
padding: 2
pred-weight: 1.0
quant-level: "8"
recon-detach: true
recon-loss: "l2"
recon-stability-weight: 0
rotate-data: false
save-dir: "experiments/finn"
scale: 0.0
shift-data: false
vae-std-tform: "exp"
stochastic: false
subsample-context:
subsample-train:
    2: 0.0
validate: true
val-freq: 450
test-pcnt: 0.2
train-on-recon: false
use-inn: false
use-pretrained-enc: false
use-wandb: true
vae: false
vgg-weight: 0
warmup-steps: 500
weight-decay: 0
zs-frac: 0.031
