defaults:
    # the "@_here_" is needed to move "fallen_sun" out of the "cmnist" subdir
    - cmnist/fallen_sun@_here_

aggregator_type: gated
bag_size: 8
batch_size: 32
# disc_reset_prob: 0.0
adv_loss_w: 0.1
enc_loss_w: 100.0
iters: 8_000
# num_discs: 3
zs_transform: round_ste
