defaults:
    # the "@_here_" is needed to move "fallen_sun" out of the "cmnist" subdir
    - cmnist/fallen_sun@_here_

aggregator_type: gated
bag_size: 256
batch_size: 1
iters: 8000
num_discs: 1
zs_transform: none
