defaults:
    # the "@_here_" is needed to move "fallen_sun" out of the "cmnist" subdir
    - cmnist/fallen_sun@_here_

aggregator_type: gated
bag_size: 36
batch_size: 7
iters: 8_000
num_disc_updates: 3
num_discs: 3
zs_transform: round_ste
