---
defaults:
  - kmeans
  - _self_
clip_version: RN50
download_root: null
ft:
  steps: 1000
  batch_size: 16
  lr: 1e-05
  val_freq: 0.25
  val_batches: 1.0
enc_batch_size: 64
gpu: 0
spherical: true
fft_cluster_init: false
supervised_cluster_init: false
n_init: 10
save_as_artifact: true
cache_encoder: false
artifact_name: nih_kmeans
