---
defaults:
  - /schema/split: base
  - defaults
  - _self_
log_dataset: ''
seed: 42
transductive: false
context_prop: 0.4
test_prop: 0.2
data_prop: null
missing_s: null
mixing_factor: 0
subsample_context: null
subsample_train: null
train_transforms: null
test_transforms: null
context_transforms: null
