---
defaults:
  - /schema/split: base
  - defaults
  - _self_
log_dataset: ''
seed: 42
transductive: false
dep_prop: 0.4
test_prop: 0.2
data_prop: null
dep_subsampling_props: null
train_subsampling_props: null
train_transforms: null
test_transforms: null
dep_transforms: null
