aggregator_type: kvq
bag_size: 8
balanced_eval: true
batch_size: 64
disc_hidden_dims: [32]
double_adv_loss: false
eval_epochs: 60
eval_on_recon: false
iters: 6000
kl_weight: 0
log_freq: 100
lr: 1.e-3
num_disc_updates: 3
num_discs: 1
oversample: true
pred_s_weight: 0.0
pred_y_weight: 1.0
train_on_recon: false
vae: false
val_freq: 500
validate: true
warmup_steps: 0
weight_decay: 0
zs_dim: 1
zs_transform: none
