---
defaults:
  - kmeans
  - _self_
clip_version: RN50
download_root: null
ft:
  steps: 2000
  batch_size: 10
  lr: 1e-05
  val_freq: 0.1
  val_batches: 1.0
enc_batch_size: 150
gpu: 0
spherical: true
fft_cluster_init: false
supervised_cluster_init: true
n_init: 10
save_as_artifact: false
cache_encoder: false
