batch_size: 1
balanced_sampling: true
model:
    hidden_dim: null
    num_hidden: 1
steps: 10000
opt:
    lr: 1.e-4
    scheduler_cls: torch.optim.lr_scheduler.CosineAnnealingLR
    scheduler_kwargs:
        T_max: ${ eval.steps }
        eta_min: 5e-7
