---
defaults:
  - random
  - _self_
# log_dataset: ''
seed: 42
transductive: false
dep_prop: 0.4
test_prop: 0.2
# data_prop: null
dep_subsampling_props:
    0:
        0: 0.7
        1: 0.4
    1:
        0: 0.2

train_subsampling_props:
    0:
        1: 0.3
    1:
        0: 0.0
train_transforms:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: 28
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Pad
          padding: 2
        - _target_: torchvision.transforms.Normalize
          mean: [ 0.5, 0.5, 0.5 ]
          std: [ 0.5, 0.5, 0.5 ]

test_transforms:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: 28
        - _target_: torchvision.transforms.ToTensor
        - _target_: torchvision.transforms.Pad
          padding: 2
        - _target_: torchvision.transforms.Normalize
          mean: [ 0.5, 0.5, 0.5 ]
          std: [ 0.5, 0.5, 0.5 ]
dep_transforms: null
