batch_size: 256
cl_hidden_dims:
    - 256
enc_epochs: 10
enc_lr: 3.e-4
encoder: ae
epochs: 50
factorized_s_y: true
k_num: 8
kl_weight: 1.e-4
log_freq: 50
pseudo_labeler: ranking
sup_bce_weight: 0
val_freq: 10
