defaults:
  - config_schema
  # - dm: base/default
  # - wandb: base/default
  # - split: random
  # - ae: base/default
  # - ae_arch: simple
  # - alg: base/default
  # - disc: base/default
  - disc_arch:
  - ds:
  # - eval: base/default
  - labeller:
  # - scorer: none
  - _self_
