---
name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  format_with_black:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install black
      run: |
        pip install black
    - name: Format with black
      run: |
        python -m black --check .

  format_with_isort:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install isort
      run: |
        pip install isort
    - name: Format with isort
      run: |
        isort --diff --check .
